[tool.poetry]
name = "golem-ray"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "golem_ray"}]

[tool.poetry.dependencies]
python = "^3.10"
ray = "2.5.0"
golem-core = "0.1.0"
golem-api-python = "0.1.1"
aiohttp = "3.8.4"
aiohttp-session = "2.12.0"
cryptography = "41.0.1"
to = "^0.3"
install = "^1.3.5"
with = "^0.0.7"
by = "^0.0.4"
the = "^0.1.5"
aiohttp-pydantic = "1.12.2"
python-dotenv = "1.0.0"
requests = "2.31.0"
spacy = "3.5.3"
pandas = ">=2.0.3,<2.1.0"
setuptools = ">=68.0.0,<68.1.0"
click = ">=8.1.3,<8.2.0"
yarl = ">=1.9.2,<1.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
