[tool.poetry]
name = "golem-ray"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "golem_ray"}]

[tool.poetry.dependencies]
python = "^3.8"

ray = "^2.6"
golem-api-python = "^0.1.1"
aiohttp = "^3"
python-dotenv = "^1"
requests = "^2"
click = "^8"
pydantic = "^2"

setuptools = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
